/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-08-07 19:00:49 UTC)
 * on 2013-08-13 at 20:13:14 UTC 
 * Modify at your own risk.
 */

package us.quizz.www.crowdquiz.entities.quizz;

/**
 * Service definition for Quizz (v1).
 *
 * <p>
 * The API for Quizz.us
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link QuizzRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Quizz extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.15.0-rc of the  library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://crowd-power.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "quizz/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Quizz(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Quizz(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getQuiz".
   *
   * This request holds the parameters needed by the the quizz server.  After setting any optional
   * parameters, call the {@link GetQuiz#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public GetQuiz getQuiz(java.lang.String id) throws java.io.IOException {
    GetQuiz result = new GetQuiz(id);
    initialize(result);
    return result;
  }

  public class GetQuiz extends QuizzRequest<us.quizz.www.crowdquiz.entities.quizz.model.Quiz> {

    private static final String REST_PATH = "quiz/{id}";

    /**
     * Create a request for the method "getQuiz".
     *
     * This request holds the parameters needed by the the quizz server.  After setting any optional
     * parameters, call the {@link GetQuiz#execute()} method to invoke the remote operation. <p>
     * {@link
     * GetQuiz#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
     * be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetQuiz(java.lang.String id) {
      super(Quizz.this, "GET", REST_PATH, null, us.quizz.www.crowdquiz.entities.quizz.model.Quiz.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetQuiz setAlt(java.lang.String alt) {
      return (GetQuiz) super.setAlt(alt);
    }

    @Override
    public GetQuiz setFields(java.lang.String fields) {
      return (GetQuiz) super.setFields(fields);
    }

    @Override
    public GetQuiz setKey(java.lang.String key) {
      return (GetQuiz) super.setKey(key);
    }

    @Override
    public GetQuiz setOauthToken(java.lang.String oauthToken) {
      return (GetQuiz) super.setOauthToken(oauthToken);
    }

    @Override
    public GetQuiz setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetQuiz) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetQuiz setQuotaUser(java.lang.String quotaUser) {
      return (GetQuiz) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetQuiz setUserIp(java.lang.String userIp) {
      return (GetQuiz) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public GetQuiz setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public GetQuiz set(String parameterName, Object value) {
      return (GetQuiz) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "getQuizPerformance".
   *
   * This request holds the parameters needed by the the quizz server.  After setting any optional
   * parameters, call the {@link GetQuizPerformance#execute()} method to invoke the remote operation.
   *
   * @param quiz
   * @param user
   * @return the request
   */
  public GetQuizPerformance getQuizPerformance(java.lang.String quiz, java.lang.String user) throws java.io.IOException {
    GetQuizPerformance result = new GetQuizPerformance(quiz, user);
    initialize(result);
    return result;
  }

  public class GetQuizPerformance extends QuizzRequest<us.quizz.www.crowdquiz.entities.quizz.model.QuizPerformance> {

    private static final String REST_PATH = "quizperformance/quiz/{quiz}/user/{user}";

    /**
     * Create a request for the method "getQuizPerformance".
     *
     * This request holds the parameters needed by the the quizz server.  After setting any optional
     * parameters, call the {@link GetQuizPerformance#execute()} method to invoke the remote
     * operation. <p> {@link GetQuizPerformance#initialize(com.google.api.client.googleapis.services.A
     * bstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param quiz
     * @param user
     * @since 1.13
     */
    protected GetQuizPerformance(java.lang.String quiz, java.lang.String user) {
      super(Quizz.this, "GET", REST_PATH, null, us.quizz.www.crowdquiz.entities.quizz.model.QuizPerformance.class);
      this.quiz = com.google.api.client.util.Preconditions.checkNotNull(quiz, "Required parameter quiz must be specified.");
      this.user = com.google.api.client.util.Preconditions.checkNotNull(user, "Required parameter user must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetQuizPerformance setAlt(java.lang.String alt) {
      return (GetQuizPerformance) super.setAlt(alt);
    }

    @Override
    public GetQuizPerformance setFields(java.lang.String fields) {
      return (GetQuizPerformance) super.setFields(fields);
    }

    @Override
    public GetQuizPerformance setKey(java.lang.String key) {
      return (GetQuizPerformance) super.setKey(key);
    }

    @Override
    public GetQuizPerformance setOauthToken(java.lang.String oauthToken) {
      return (GetQuizPerformance) super.setOauthToken(oauthToken);
    }

    @Override
    public GetQuizPerformance setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetQuizPerformance) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetQuizPerformance setQuotaUser(java.lang.String quotaUser) {
      return (GetQuizPerformance) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetQuizPerformance setUserIp(java.lang.String userIp) {
      return (GetQuizPerformance) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String quiz;

    /**

     */
    public java.lang.String getQuiz() {
      return quiz;
    }

    public GetQuizPerformance setQuiz(java.lang.String quiz) {
      this.quiz = quiz;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String user;

    /**

     */
    public java.lang.String getUser() {
      return user;
    }

    public GetQuizPerformance setUser(java.lang.String user) {
      this.user = user;
      return this;
    }

    @Override
    public GetQuizPerformance set(String parameterName, Object value) {
      return (GetQuizPerformance) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertQuiz".
   *
   * This request holds the parameters needed by the the quizz server.  After setting any optional
   * parameters, call the {@link InsertQuiz#execute()} method to invoke the remote operation.
   *
   * @param content the {@link us.quizz.www.crowdquiz.entities.quizz.model.Quiz}
   * @return the request
   */
  public InsertQuiz insertQuiz(us.quizz.www.crowdquiz.entities.quizz.model.Quiz content) throws java.io.IOException {
    InsertQuiz result = new InsertQuiz(content);
    initialize(result);
    return result;
  }

  public class InsertQuiz extends QuizzRequest<us.quizz.www.crowdquiz.entities.quizz.model.Quiz> {

    private static final String REST_PATH = "quiz";

    /**
     * Create a request for the method "insertQuiz".
     *
     * This request holds the parameters needed by the the quizz server.  After setting any optional
     * parameters, call the {@link InsertQuiz#execute()} method to invoke the remote operation. <p>
     * {@link
     * InsertQuiz#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link us.quizz.www.crowdquiz.entities.quizz.model.Quiz}
     * @since 1.13
     */
    protected InsertQuiz(us.quizz.www.crowdquiz.entities.quizz.model.Quiz content) {
      super(Quizz.this, "POST", REST_PATH, content, us.quizz.www.crowdquiz.entities.quizz.model.Quiz.class);
    }

    @Override
    public InsertQuiz setAlt(java.lang.String alt) {
      return (InsertQuiz) super.setAlt(alt);
    }

    @Override
    public InsertQuiz setFields(java.lang.String fields) {
      return (InsertQuiz) super.setFields(fields);
    }

    @Override
    public InsertQuiz setKey(java.lang.String key) {
      return (InsertQuiz) super.setKey(key);
    }

    @Override
    public InsertQuiz setOauthToken(java.lang.String oauthToken) {
      return (InsertQuiz) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertQuiz setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertQuiz) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertQuiz setQuotaUser(java.lang.String quotaUser) {
      return (InsertQuiz) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertQuiz setUserIp(java.lang.String userIp) {
      return (InsertQuiz) super.setUserIp(userIp);
    }

    @Override
    public InsertQuiz set(String parameterName, Object value) {
      return (InsertQuiz) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertQuizPerformance".
   *
   * This request holds the parameters needed by the the quizz server.  After setting any optional
   * parameters, call the {@link InsertQuizPerformance#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link us.quizz.www.crowdquiz.entities.quizz.model.QuizPerformance}
   * @return the request
   */
  public InsertQuizPerformance insertQuizPerformance(us.quizz.www.crowdquiz.entities.quizz.model.QuizPerformance content) throws java.io.IOException {
    InsertQuizPerformance result = new InsertQuizPerformance(content);
    initialize(result);
    return result;
  }

  public class InsertQuizPerformance extends QuizzRequest<us.quizz.www.crowdquiz.entities.quizz.model.QuizPerformance> {

    private static final String REST_PATH = "quizperformance";

    /**
     * Create a request for the method "insertQuizPerformance".
     *
     * This request holds the parameters needed by the the quizz server.  After setting any optional
     * parameters, call the {@link InsertQuizPerformance#execute()} method to invoke the remote
     * operation. <p> {@link InsertQuizPerformance#initialize(com.google.api.client.googleapis.service
     * s.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param content the {@link us.quizz.www.crowdquiz.entities.quizz.model.QuizPerformance}
     * @since 1.13
     */
    protected InsertQuizPerformance(us.quizz.www.crowdquiz.entities.quizz.model.QuizPerformance content) {
      super(Quizz.this, "POST", REST_PATH, content, us.quizz.www.crowdquiz.entities.quizz.model.QuizPerformance.class);
    }

    @Override
    public InsertQuizPerformance setAlt(java.lang.String alt) {
      return (InsertQuizPerformance) super.setAlt(alt);
    }

    @Override
    public InsertQuizPerformance setFields(java.lang.String fields) {
      return (InsertQuizPerformance) super.setFields(fields);
    }

    @Override
    public InsertQuizPerformance setKey(java.lang.String key) {
      return (InsertQuizPerformance) super.setKey(key);
    }

    @Override
    public InsertQuizPerformance setOauthToken(java.lang.String oauthToken) {
      return (InsertQuizPerformance) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertQuizPerformance setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertQuizPerformance) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertQuizPerformance setQuotaUser(java.lang.String quotaUser) {
      return (InsertQuizPerformance) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertQuizPerformance setUserIp(java.lang.String userIp) {
      return (InsertQuizPerformance) super.setUserIp(userIp);
    }

    @Override
    public InsertQuizPerformance set(String parameterName, Object value) {
      return (InsertQuizPerformance) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listQuiz".
   *
   * This request holds the parameters needed by the the quizz server.  After setting any optional
   * parameters, call the {@link ListQuiz#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public ListQuiz listQuiz() throws java.io.IOException {
    ListQuiz result = new ListQuiz();
    initialize(result);
    return result;
  }

  public class ListQuiz extends QuizzRequest<us.quizz.www.crowdquiz.entities.quizz.model.CollectionResponseQuiz> {

    private static final String REST_PATH = "quiz";

    /**
     * Create a request for the method "listQuiz".
     *
     * This request holds the parameters needed by the the quizz server.  After setting any optional
     * parameters, call the {@link ListQuiz#execute()} method to invoke the remote operation. <p>
     * {@link
     * ListQuiz#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListQuiz() {
      super(Quizz.this, "GET", REST_PATH, null, us.quizz.www.crowdquiz.entities.quizz.model.CollectionResponseQuiz.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListQuiz setAlt(java.lang.String alt) {
      return (ListQuiz) super.setAlt(alt);
    }

    @Override
    public ListQuiz setFields(java.lang.String fields) {
      return (ListQuiz) super.setFields(fields);
    }

    @Override
    public ListQuiz setKey(java.lang.String key) {
      return (ListQuiz) super.setKey(key);
    }

    @Override
    public ListQuiz setOauthToken(java.lang.String oauthToken) {
      return (ListQuiz) super.setOauthToken(oauthToken);
    }

    @Override
    public ListQuiz setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListQuiz) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListQuiz setQuotaUser(java.lang.String quotaUser) {
      return (ListQuiz) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListQuiz setUserIp(java.lang.String userIp) {
      return (ListQuiz) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListQuiz setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListQuiz setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListQuiz set(String parameterName, Object value) {
      return (ListQuiz) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listQuizPerformance".
   *
   * This request holds the parameters needed by the the quizz server.  After setting any optional
   * parameters, call the {@link ListQuizPerformance#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public ListQuizPerformance listQuizPerformance() throws java.io.IOException {
    ListQuizPerformance result = new ListQuizPerformance();
    initialize(result);
    return result;
  }

  public class ListQuizPerformance extends QuizzRequest<us.quizz.www.crowdquiz.entities.quizz.model.CollectionResponseQuizPerformance> {

    private static final String REST_PATH = "quizperformance";

    /**
     * Create a request for the method "listQuizPerformance".
     *
     * This request holds the parameters needed by the the quizz server.  After setting any optional
     * parameters, call the {@link ListQuizPerformance#execute()} method to invoke the remote
     * operation. <p> {@link ListQuizPerformance#initialize(com.google.api.client.googleapis.services.
     * AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListQuizPerformance() {
      super(Quizz.this, "GET", REST_PATH, null, us.quizz.www.crowdquiz.entities.quizz.model.CollectionResponseQuizPerformance.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListQuizPerformance setAlt(java.lang.String alt) {
      return (ListQuizPerformance) super.setAlt(alt);
    }

    @Override
    public ListQuizPerformance setFields(java.lang.String fields) {
      return (ListQuizPerformance) super.setFields(fields);
    }

    @Override
    public ListQuizPerformance setKey(java.lang.String key) {
      return (ListQuizPerformance) super.setKey(key);
    }

    @Override
    public ListQuizPerformance setOauthToken(java.lang.String oauthToken) {
      return (ListQuizPerformance) super.setOauthToken(oauthToken);
    }

    @Override
    public ListQuizPerformance setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListQuizPerformance) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListQuizPerformance setQuotaUser(java.lang.String quotaUser) {
      return (ListQuizPerformance) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListQuizPerformance setUserIp(java.lang.String userIp) {
      return (ListQuizPerformance) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListQuizPerformance setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListQuizPerformance setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListQuizPerformance set(String parameterName, Object value) {
      return (ListQuizPerformance) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listQuizPerformanceByUser".
   *
   * This request holds the parameters needed by the the quizz server.  After setting any optional
   * parameters, call the {@link ListQuizPerformanceByUser#execute()} method to invoke the remote
   * operation.
   *
   * @param user
   * @return the request
   */
  public ListQuizPerformanceByUser listQuizPerformanceByUser(java.lang.String user) throws java.io.IOException {
    ListQuizPerformanceByUser result = new ListQuizPerformanceByUser(user);
    initialize(result);
    return result;
  }

  public class ListQuizPerformanceByUser extends QuizzRequest<us.quizz.www.crowdquiz.entities.quizz.model.CollectionResponseQuizPerformance> {

    private static final String REST_PATH = "quizperformance/user/{user}";

    /**
     * Create a request for the method "listQuizPerformanceByUser".
     *
     * This request holds the parameters needed by the the quizz server.  After setting any optional
     * parameters, call the {@link ListQuizPerformanceByUser#execute()} method to invoke the remote
     * operation. <p> {@link ListQuizPerformanceByUser#initialize(com.google.api.client.googleapis.ser
     * vices.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @param user
     * @since 1.13
     */
    protected ListQuizPerformanceByUser(java.lang.String user) {
      super(Quizz.this, "GET", REST_PATH, null, us.quizz.www.crowdquiz.entities.quizz.model.CollectionResponseQuizPerformance.class);
      this.user = com.google.api.client.util.Preconditions.checkNotNull(user, "Required parameter user must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListQuizPerformanceByUser setAlt(java.lang.String alt) {
      return (ListQuizPerformanceByUser) super.setAlt(alt);
    }

    @Override
    public ListQuizPerformanceByUser setFields(java.lang.String fields) {
      return (ListQuizPerformanceByUser) super.setFields(fields);
    }

    @Override
    public ListQuizPerformanceByUser setKey(java.lang.String key) {
      return (ListQuizPerformanceByUser) super.setKey(key);
    }

    @Override
    public ListQuizPerformanceByUser setOauthToken(java.lang.String oauthToken) {
      return (ListQuizPerformanceByUser) super.setOauthToken(oauthToken);
    }

    @Override
    public ListQuizPerformanceByUser setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListQuizPerformanceByUser) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListQuizPerformanceByUser setQuotaUser(java.lang.String quotaUser) {
      return (ListQuizPerformanceByUser) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListQuizPerformanceByUser setUserIp(java.lang.String userIp) {
      return (ListQuizPerformanceByUser) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String user;

    /**

     */
    public java.lang.String getUser() {
      return user;
    }

    public ListQuizPerformanceByUser setUser(java.lang.String user) {
      this.user = user;
      return this;
    }

    @Override
    public ListQuizPerformanceByUser set(String parameterName, Object value) {
      return (ListQuizPerformanceByUser) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeQuiz".
   *
   * This request holds the parameters needed by the the quizz server.  After setting any optional
   * parameters, call the {@link RemoveQuiz#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public RemoveQuiz removeQuiz(java.lang.String id) throws java.io.IOException {
    RemoveQuiz result = new RemoveQuiz(id);
    initialize(result);
    return result;
  }

  public class RemoveQuiz extends QuizzRequest<Void> {

    private static final String REST_PATH = "quiz/{id}";

    /**
     * Create a request for the method "removeQuiz".
     *
     * This request holds the parameters needed by the the quizz server.  After setting any optional
     * parameters, call the {@link RemoveQuiz#execute()} method to invoke the remote operation. <p>
     * {@link
     * RemoveQuiz#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveQuiz(java.lang.String id) {
      super(Quizz.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveQuiz setAlt(java.lang.String alt) {
      return (RemoveQuiz) super.setAlt(alt);
    }

    @Override
    public RemoveQuiz setFields(java.lang.String fields) {
      return (RemoveQuiz) super.setFields(fields);
    }

    @Override
    public RemoveQuiz setKey(java.lang.String key) {
      return (RemoveQuiz) super.setKey(key);
    }

    @Override
    public RemoveQuiz setOauthToken(java.lang.String oauthToken) {
      return (RemoveQuiz) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveQuiz setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveQuiz) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveQuiz setQuotaUser(java.lang.String quotaUser) {
      return (RemoveQuiz) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveQuiz setUserIp(java.lang.String userIp) {
      return (RemoveQuiz) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public RemoveQuiz setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveQuiz set(String parameterName, Object value) {
      return (RemoveQuiz) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeQuizPerformance".
   *
   * This request holds the parameters needed by the the quizz server.  After setting any optional
   * parameters, call the {@link RemoveQuizPerformance#execute()} method to invoke the remote
   * operation.
   *
   * @param quizid
   * @param userid
   * @return the request
   */
  public RemoveQuizPerformance removeQuizPerformance(java.lang.String quizid, java.lang.String userid) throws java.io.IOException {
    RemoveQuizPerformance result = new RemoveQuizPerformance(quizid, userid);
    initialize(result);
    return result;
  }

  public class RemoveQuizPerformance extends QuizzRequest<Void> {

    private static final String REST_PATH = "quizperformance/{quizid}/{userid}";

    /**
     * Create a request for the method "removeQuizPerformance".
     *
     * This request holds the parameters needed by the the quizz server.  After setting any optional
     * parameters, call the {@link RemoveQuizPerformance#execute()} method to invoke the remote
     * operation. <p> {@link RemoveQuizPerformance#initialize(com.google.api.client.googleapis.service
     * s.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param quizid
     * @param userid
     * @since 1.13
     */
    protected RemoveQuizPerformance(java.lang.String quizid, java.lang.String userid) {
      super(Quizz.this, "DELETE", REST_PATH, null, Void.class);
      this.quizid = com.google.api.client.util.Preconditions.checkNotNull(quizid, "Required parameter quizid must be specified.");
      this.userid = com.google.api.client.util.Preconditions.checkNotNull(userid, "Required parameter userid must be specified.");
    }

    @Override
    public RemoveQuizPerformance setAlt(java.lang.String alt) {
      return (RemoveQuizPerformance) super.setAlt(alt);
    }

    @Override
    public RemoveQuizPerformance setFields(java.lang.String fields) {
      return (RemoveQuizPerformance) super.setFields(fields);
    }

    @Override
    public RemoveQuizPerformance setKey(java.lang.String key) {
      return (RemoveQuizPerformance) super.setKey(key);
    }

    @Override
    public RemoveQuizPerformance setOauthToken(java.lang.String oauthToken) {
      return (RemoveQuizPerformance) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveQuizPerformance setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveQuizPerformance) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveQuizPerformance setQuotaUser(java.lang.String quotaUser) {
      return (RemoveQuizPerformance) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveQuizPerformance setUserIp(java.lang.String userIp) {
      return (RemoveQuizPerformance) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String quizid;

    /**

     */
    public java.lang.String getQuizid() {
      return quizid;
    }

    public RemoveQuizPerformance setQuizid(java.lang.String quizid) {
      this.quizid = quizid;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String userid;

    /**

     */
    public java.lang.String getUserid() {
      return userid;
    }

    public RemoveQuizPerformance setUserid(java.lang.String userid) {
      this.userid = userid;
      return this;
    }

    @Override
    public RemoveQuizPerformance set(String parameterName, Object value) {
      return (RemoveQuizPerformance) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateQuiz".
   *
   * This request holds the parameters needed by the the quizz server.  After setting any optional
   * parameters, call the {@link UpdateQuiz#execute()} method to invoke the remote operation.
   *
   * @param content the {@link us.quizz.www.crowdquiz.entities.quizz.model.Quiz}
   * @return the request
   */
  public UpdateQuiz updateQuiz(us.quizz.www.crowdquiz.entities.quizz.model.Quiz content) throws java.io.IOException {
    UpdateQuiz result = new UpdateQuiz(content);
    initialize(result);
    return result;
  }

  public class UpdateQuiz extends QuizzRequest<us.quizz.www.crowdquiz.entities.quizz.model.Quiz> {

    private static final String REST_PATH = "quiz";

    /**
     * Create a request for the method "updateQuiz".
     *
     * This request holds the parameters needed by the the quizz server.  After setting any optional
     * parameters, call the {@link UpdateQuiz#execute()} method to invoke the remote operation. <p>
     * {@link
     * UpdateQuiz#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link us.quizz.www.crowdquiz.entities.quizz.model.Quiz}
     * @since 1.13
     */
    protected UpdateQuiz(us.quizz.www.crowdquiz.entities.quizz.model.Quiz content) {
      super(Quizz.this, "PUT", REST_PATH, content, us.quizz.www.crowdquiz.entities.quizz.model.Quiz.class);
    }

    @Override
    public UpdateQuiz setAlt(java.lang.String alt) {
      return (UpdateQuiz) super.setAlt(alt);
    }

    @Override
    public UpdateQuiz setFields(java.lang.String fields) {
      return (UpdateQuiz) super.setFields(fields);
    }

    @Override
    public UpdateQuiz setKey(java.lang.String key) {
      return (UpdateQuiz) super.setKey(key);
    }

    @Override
    public UpdateQuiz setOauthToken(java.lang.String oauthToken) {
      return (UpdateQuiz) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateQuiz setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateQuiz) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateQuiz setQuotaUser(java.lang.String quotaUser) {
      return (UpdateQuiz) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateQuiz setUserIp(java.lang.String userIp) {
      return (UpdateQuiz) super.setUserIp(userIp);
    }

    @Override
    public UpdateQuiz set(String parameterName, Object value) {
      return (UpdateQuiz) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateQuizPerformance".
   *
   * This request holds the parameters needed by the the quizz server.  After setting any optional
   * parameters, call the {@link UpdateQuizPerformance#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link us.quizz.www.crowdquiz.entities.quizz.model.QuizPerformance}
   * @return the request
   */
  public UpdateQuizPerformance updateQuizPerformance(us.quizz.www.crowdquiz.entities.quizz.model.QuizPerformance content) throws java.io.IOException {
    UpdateQuizPerformance result = new UpdateQuizPerformance(content);
    initialize(result);
    return result;
  }

  public class UpdateQuizPerformance extends QuizzRequest<us.quizz.www.crowdquiz.entities.quizz.model.QuizPerformance> {

    private static final String REST_PATH = "quizperformance";

    /**
     * Create a request for the method "updateQuizPerformance".
     *
     * This request holds the parameters needed by the the quizz server.  After setting any optional
     * parameters, call the {@link UpdateQuizPerformance#execute()} method to invoke the remote
     * operation. <p> {@link UpdateQuizPerformance#initialize(com.google.api.client.googleapis.service
     * s.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param content the {@link us.quizz.www.crowdquiz.entities.quizz.model.QuizPerformance}
     * @since 1.13
     */
    protected UpdateQuizPerformance(us.quizz.www.crowdquiz.entities.quizz.model.QuizPerformance content) {
      super(Quizz.this, "PUT", REST_PATH, content, us.quizz.www.crowdquiz.entities.quizz.model.QuizPerformance.class);
    }

    @Override
    public UpdateQuizPerformance setAlt(java.lang.String alt) {
      return (UpdateQuizPerformance) super.setAlt(alt);
    }

    @Override
    public UpdateQuizPerformance setFields(java.lang.String fields) {
      return (UpdateQuizPerformance) super.setFields(fields);
    }

    @Override
    public UpdateQuizPerformance setKey(java.lang.String key) {
      return (UpdateQuizPerformance) super.setKey(key);
    }

    @Override
    public UpdateQuizPerformance setOauthToken(java.lang.String oauthToken) {
      return (UpdateQuizPerformance) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateQuizPerformance setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateQuizPerformance) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateQuizPerformance setQuotaUser(java.lang.String quotaUser) {
      return (UpdateQuizPerformance) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateQuizPerformance setUserIp(java.lang.String userIp) {
      return (UpdateQuizPerformance) super.setUserIp(userIp);
    }

    @Override
    public UpdateQuizPerformance set(String parameterName, Object value) {
      return (UpdateQuizPerformance) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Quizz}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Quizz}. */
    @Override
    public Quizz build() {
      return new Quizz(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link QuizzRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setQuizzRequestInitializer(
        QuizzRequestInitializer quizzRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(quizzRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
